spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/task_tracker_2}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:admin76}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update